# Build image
# $ docker build -t micropython-client -f Dockerfile.client .
#
# Run image
# $ docker run -it --rm --name micropython-client micropython-client

FROM micropython/unix:v1.18

# use "volumes" in docker-compose file to remove need of rebuilding
# COPY ./ /home
# COPY umodbus /root/.micropython/lib/umodbus

RUN micropython-dev -m upip install micropython-ulogging

CMD [ "micropython-dev", "-m", "examples/tcp_client_example.py" ]
