# Build image
# $ docker build -t micropython-host-tcp -f Dockerfile.host_tcp .
#
# Run image
# $ docker run -it --rm --name micropython-host-tcp micropython-host-tcp

FROM micropython/unix:v1.18

# use "volumes" in docker-compose file to remove need of rebuilding
# COPY ./ /home
# COPY umodbus /root/.micropython/lib/umodbus

RUN micropython-dev -m upip install micropython-ulogging

CMD [ "micropython-dev", "-m", "examples/tcp_host_example.py" ]
